# Generated by Django 5.2.4 on 2025-07-30 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigurationSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='Kunci konfigurasi (misalnya, THRESHOLD_VM_UPTIME_DAYS)', max_length=255, unique=True)),
                ('value', models.TextField(help_text='Nilai konfigurasi (bisa berupa string, JSON string, atau angka)')),
                ('description', models.TextField(blank=True, help_text='Deskripsi singkat untuk konteks konfigurasi', null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Pengaturan Konfigurasi',
                'verbose_name_plural': 'Pengaturan Konfigurasi',
                'ordering': ['key'],
            },
        ),
    ]
