# Generated by Django 5.2.4 on 2025-07-30 04:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_key', models.CharField(max_length=255, unique=True, verbose_name='Primary Key')),
                ('name', models.CharField(max_length=255, verbose_name='Virtual Machine')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address')),
                ('state', models.CharField(default='poweredOff', max_length=50, verbose_name='State')),
                ('uptime_days', models.IntegerField(blank=True, null=True, verbose_name='Uptime (Hari)')),
                ('health_score', models.IntegerField(default=100, verbose_name='Skor Kesehatan (0-100)')),
                ('cpu', models.IntegerField(default=0, verbose_name='CPU (vCPU)')),
                ('memory_gb', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Memory (GB)')),
                ('provisioned_gb', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Provisioned (GB)')),
                ('provisioned_tb', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Provisioned (TB)')),
                ('vcenter', models.CharField(max_length=100, verbose_name='vCenter')),
                ('cluster', models.CharField(max_length=100, verbose_name='Cluster')),
                ('datastore_name', models.CharField(max_length=255, verbose_name='Datastore')),
                ('criticality', models.CharField(max_length=100, verbose_name='Kritikalitas BIA')),
                ('environment', models.CharField(max_length=100, verbose_name='Environment')),
                ('app_group', models.CharField(blank=True, max_length=255, null=True, verbose_name='Aplikasi BIA')),
                ('dev_ops', models.CharField(blank=True, max_length=255, null=True, verbose_name='DEV/OPS')),
                ('guest_os', models.CharField(blank=True, max_length=255, null=True, verbose_name='Guest OS')),
                ('host', models.CharField(blank=True, max_length=255, null=True, verbose_name='Host')),
                ('provisioning_ticket_no', models.CharField(blank=True, max_length=100, null=True, verbose_name='No Tiket Provisioning')),
                ('setup_date', models.DateField(blank=True, null=True, verbose_name='Tanggal Setup')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Virtual Machine',
                'verbose_name_plural': 'Virtual Machines',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['primary_key'], name='vms_vm_primary_691888_idx'), models.Index(fields=['name'], name='vms_vm_name_a3e922_idx'), models.Index(fields=['ip_address'], name='vms_vm_ip_addr_a6bd93_idx'), models.Index(fields=['cluster'], name='vms_vm_cluster_ff24a9_idx'), models.Index(fields=['datastore_name'], name='vms_vm_datasto_104958_idx')],
            },
        ),
        migrations.CreateModel(
            name='VMNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_text', models.TextField(verbose_name='Isi Catatan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Timestamp Update')),
                ('updated_by_telegram_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nama Telegram User (Fallback)')),
                ('updated_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='User Update')),
                ('vm', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='note', to='vms.vm', verbose_name='Virtual Machine')),
            ],
            options={
                'verbose_name': 'Catatan VM',
                'verbose_name_plural': 'Catatan VM',
                'ordering': ['vm__name'],
            },
        ),
        migrations.CreateModel(
            name='VMHistoryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vm_primary_key', models.CharField(max_length=255, verbose_name='VM Primary Key')),
                ('vm_name_at_log', models.CharField(max_length=255, verbose_name='Nama VM Saat Log')),
                ('log_timestamp', models.DateTimeField(verbose_name='Timestamp Log')),
                ('action', models.CharField(max_length=50, verbose_name='Aksi (PENAMBAHAN, MODIFIKASI, PENGHAPUSAN)')),
                ('sheet_source', models.CharField(max_length=100, verbose_name='Sumber Sheet')),
                ('old_value', models.TextField(blank=True, null=True, verbose_name='Nilai Lama')),
                ('new_value', models.TextField(blank=True, null=True, verbose_name='Nilai Baru')),
                ('detail', models.TextField(blank=True, null=True, verbose_name='Detail Perubahan')),
                ('entity_type', models.CharField(max_length=50, verbose_name='Tipe Entitas (VM/Datastore)')),
                ('vm', models.ForeignKey(blank=True, help_text='Relasi ke VM yang berubah (jika masih ada)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history_logs', to='vms.vm')),
            ],
            options={
                'verbose_name': 'Log Riwayat VM/Datastore',
                'verbose_name_plural': 'Log Riwayat VM/Datastore',
                'ordering': ['-log_timestamp'],
                'indexes': [models.Index(fields=['vm_primary_key'], name='vms_vmhisto_vm_prim_d751f2_idx'), models.Index(fields=['log_timestamp'], name='vms_vmhisto_log_tim_82e963_idx'), models.Index(fields=['action'], name='vms_vmhisto_action_51165f_idx')],
            },
        ),
    ]
