# Generated by Django 5.2.4 on 2025-07-30 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CriticalityScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=100, unique=True, verbose_name='Level Kritikalitas (mis: CRITICAL, HIGH)')),
                ('score_value', models.IntegerField(verbose_name='Nilai Skor')),
            ],
            options={
                'verbose_name': 'Skor Kritikalitas',
                'verbose_name_plural': 'Skor Kritikalitas',
            },
        ),
        migrations.CreateModel(
            name='DataExclusionKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=100, unique=True, verbose_name='Kata Kunci Pengecualian Datastore')),
            ],
            options={
                'verbose_name': 'Kata Kunci Pengecualian Data',
                'verbose_name_plural': 'Kata Kunci Pengecualian Data',
            },
        ),
        migrations.CreateModel(
            name='EnvironmentMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=100, unique=True, verbose_name='Kata Kunci di Nama Datastore')),
                ('environment_name', models.CharField(max_length=100, verbose_name='Nama Environment')),
            ],
            options={
                'verbose_name': 'Pemetaan Environment',
                'verbose_name_plural': 'Pemetaan Environment',
            },
        ),
        migrations.CreateModel(
            name='StorageAliasMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_key', models.CharField(max_length=100, unique=True, verbose_name='Kunci Utama Storage (mis: VSPA)')),
                ('aliases', models.JSONField(default=list, help_text='Daftar alias untuk storage ini (JSON Array, mis: ["VSP", "HPE VSP A"])')),
            ],
            options={
                'verbose_name': 'Pemetaan Alias Storage',
                'verbose_name_plural': 'Pemetaan Alias Storage',
            },
        ),
        migrations.CreateModel(
            name='StorageCapacityMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storage_alias', models.CharField(max_length=100, unique=True, verbose_name='Alias Storage')),
                ('total_capacity_tb', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total Kapasitas (TB)')),
            ],
            options={
                'verbose_name': 'Kapasitas Storage',
                'verbose_name_plural': 'Kapasitas Storage',
            },
        ),
        migrations.CreateModel(
            name='SystemLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255, unique=True, verbose_name='Kunci Batasan Sistem (mis: LOG_CHANGE_ARCHIVE_THRESHOLD)')),
                ('value', models.TextField(help_text='Nilai batasan (bisa angka, JSON string, dll.)')),
            ],
            options={
                'verbose_name': 'Batasan Sistem',
                'verbose_name_plural': 'Batasan Sistem',
            },
        ),
        migrations.CreateModel(
            name='ThresholdSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255, unique=True, verbose_name='Kunci Threshold (mis: THRESHOLD_DS_USED_PERCENT)')),
                ('value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Nilai Threshold')),
            ],
            options={
                'verbose_name': 'Pengaturan Threshold',
                'verbose_name_plural': 'Pengaturan Threshold',
            },
        ),
    ]
