# Generated by Django 5.2.4 on 2025-07-30 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClusterPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cluster_name', models.CharField(max_length=100, unique=True, verbose_name='Nama Cluster')),
                ('physical_cpu_cores', models.IntegerField(verbose_name='Physical CPU Cores')),
                ('cpu_overcommit_ratio', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='CPU Overcommit Ratio')),
                ('physical_memory_tb', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Physical Memory (TB)')),
                ('memory_overcommit_ratio', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Memory Overcommit Ratio')),
            ],
            options={
                'verbose_name': 'Kebijakan Overcommit Cluster',
                'verbose_name_plural': 'Kebijakan Overcommit Cluster',
            },
        ),
        migrations.CreateModel(
            name='MigrationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recognized_type', models.CharField(max_length=100, unique=True, verbose_name='Tipe Teridentifikasi (mis: VSPA)')),
                ('alias', models.CharField(blank=True, help_text='Alias Tipe (opsional)', max_length=100, null=True)),
                ('priority_destinations', models.JSONField(default=list, help_text='Daftar tipe tujuan prioritas (JSON Array)')),
            ],
            options={
                'verbose_name': 'Aturan Migrasi',
                'verbose_name_plural': 'Aturan Migrasi',
            },
        ),
        migrations.CreateModel(
            name='ProvisioningRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criticality', models.CharField(max_length=100, unique=True, verbose_name='Kritikalitas (mis: CRITICAL, DEFAULT)')),
                ('io_profile', models.CharField(default='*', max_length=50, verbose_name='Profil I/O (mis: High, Normal, *)')),
                ('vcenter_target', models.CharField(max_length=100, verbose_name='vCenter Target')),
                ('priority1_clusters', models.JSONField(default=list, help_text='Klaster Prioritas 1 (JSON Array)')),
                ('priority2_clusters', models.JSONField(default=list, help_text='Klaster Prioritas 2 (JSON Array)')),
                ('priority3_clusters', models.JSONField(default=list, help_text='Klaster Prioritas 3 (JSON Array)')),
                ('excluded_clusters', models.JSONField(blank=True, default=list, help_text='Klaster yang Dikecualikan (JSON Array)')),
                ('storage_priority1', models.JSONField(default=list, help_text='Tipe Storage Prioritas 1 (JSON Array)')),
                ('storage_priority2', models.JSONField(default=list, help_text='Tipe Storage Prioritas 2 (JSON Array)')),
            ],
            options={
                'verbose_name': 'Aturan Provisioning',
                'verbose_name_plural': 'Aturan Provisioning',
            },
        ),
    ]
