# Generated by Django 5.2.4 on 2025-07-30 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_id', models.CharField(max_length=100, unique=True, verbose_name='ID Tiket')),
                ('vm_name', models.CharField(max_length=255, verbose_name='Nama VM Terkait')),
                ('criticality', models.CharField(blank=True, max_length=100, null=True, verbose_name='Kritikalitas VM')),
                ('link', models.URLField(max_length=500, verbose_name='Link Tiket')),
                ('category', models.CharField(max_length=100, verbose_name='Kategori Tiket')),
                ('created_date', models.DateField(blank=True, null=True, verbose_name='Tanggal Buat')),
                ('follow_up_date', models.DateField(blank=True, null=True, verbose_name='Tanggal Follow Up')),
                ('status', models.CharField(max_length=100, verbose_name='Status Tiket')),
                ('action_needed', models.TextField(blank=True, null=True, verbose_name='Action Needed')),
                ('done_date', models.DateField(blank=True, null=True, verbose_name='Tanggal Selesai')),
                ('dev_ops', models.CharField(blank=True, max_length=255, null=True, verbose_name='DEV/OPS Penanggung Jawab')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Keterangan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tiket Utilisasi',
                'verbose_name_plural': 'Tiket Utilisasi',
                'ordering': ['-created_date'],
                'indexes': [models.Index(fields=['ticket_id'], name='tickets_tic_ticket__5a4a00_idx'), models.Index(fields=['vm_name'], name='tickets_tic_vm_name_16fe0c_idx'), models.Index(fields=['status'], name='tickets_tic_status_0e5646_idx'), models.Index(fields=['follow_up_date'], name='tickets_tic_follow__be8378_idx')],
            },
        ),
    ]
